# Generated by Django 3.2 on 2023-07-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230726_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='consecutive',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
