# Generated by Django 3.2 on 2023-07-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_consecutive_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='consecutive',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='consecutive',
            name='file',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='consecutive',
            name='finish',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='consecutive',
            name='progres',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consecutive',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
