# Generated by Django 3.2 on 2023-07-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230726_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consecutive',
            name='finish',
            field=models.BooleanField(default=False),
        ),
    ]
