# Generated by Django 3.2 on 2024-06-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_proxy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movil',
            name='conse',
        ),
        migrations.AddField(
            model_name='movil',
            name='file',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
