# Generated by Django 3.2 on 2024-06-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20240601_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='movil',
            name='ip',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
