# Generated by Django 3.2 on 2024-06-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20240605_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
