# Generated by Django 3.2 on 2024-06-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_proxy_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockip',
            name='reintent',
            field=models.IntegerField(default=1),
        ),
    ]
