# Generated by Django 3.2 on 2024-07-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_blockip_reintent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proxy',
            old_name='port',
            new_name='port_max',
        ),
        migrations.AddField(
            model_name='proxy',
            name='port_min',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
