# Generated by Django 5.1 on 2024-08-26 06:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20240722_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='movil',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
