# Generated by Django 5.1 on 2024-10-15 22:39

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_movil_fecha_hora'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movil',
            name='fecha_hora',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movil',
            name='number',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='movil',
            index=models.Index(fields=['number'], name='app_movil_number_9e1f2a_idx'),
        ),
    ]
