# Generated by Django 5.1 on 2025-04-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_movil_fecha_hora_alter_movil_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='username',
            field=models.TextField(),
        ),
    ]
