# Generated by Django 5.1 on 2025-12-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_proxy_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consecutive',
            name='finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='consecutive',
            table='app_consecutive',
        ),
    ]
