"""
Django settings for apimovil project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path
from celery.schedules import crontab

BASE_DIR = Path(__file__).resolve().parent.parent
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]

# Cambia esto para que apunte a un directorio diferente, por ejemplo 'static'
#STATICFILES_DIRS = [
#    os.path.join(BASE_DIR, "static")
#]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-76zv-f6+^m43)2#17uq@vo^^++*z5t(q45+j+6wwk2-e$hli&='
SECRET_KEY = 'django-insecure-5g@zimt&5l^(xqwv$q%7-_zk%p+j46whmejj$yra-+i5sy-2##'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.sessions',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    #'django.middleware.locale.LocaleMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'apimovil.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'apimovil.wsgi.application'

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 1209600  # 2 semanas
SESSION_COOKIE_SECURE = False  # No marcar la cookie de sesión como segura

CSRF_COOKIE_SECURE = False  # No marcar la cookie CSRF como segura

CSRF_TRUSTED_ORIGINS = [
    'https://api.masterfilter.es',
    'https://www.masterfilter.es'
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    'http://185.47.131.53:8000',  # Permite solicitudes desde el puerto 8000
    'http://185.47.131.53',
    'https://www.masterfilter.es',
    'https://api.masterfilter.es',
    'http://www.masterfilter.es',
]

SECURE_SSL_REDIRECT = False  # No redirigir a HTTPS
SECURE_PROXY_SSL_HEADER = None

STATICFILES_STORAGE = "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
#CELERY_WORKER_PREFETCH_MULTIPLIER = 1
#CELERY_TASK_ACKS_LATE = True
#CELERY_TASK_SOFT_TIME_LIMIT = 45
#CELERY_TASK_TIME_LIMIT = 60
#CELERY_BROKER_POOL_LIMIT = 10
#CELERY_BROKER_CONNECTION_TIMEOUT = 30
#CELERY_TASK_ANNOTATIONS = {'*': {'max_retries': 3, 'rate_limit': '10/m'}}

# Configuración de Celery Beat
CELERY_BEAT_SCHEDULE = {
    'process_incomplete_files_every_30_minutes': {
        'task': 'app.tasks.process_incomplete_files_task',
        'schedule': crontab(minute='*/5'),  # Ejecutar cada 30 minutos
    },
}

# Configuración de Celery
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Usando Redis como broker
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'  # Redis también como backend de resultados



# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

#state = False
#if state:
#    # Postgresql
#    DATABASES = {
#        'default': {
#            'ENGINE': 'django.db.backends.postgresql_psycopg2',
#            'NAME': 'postgres',
#            'USER': 'postgres',
#            'PASSWORD': 'admin',
#            'HOST': '0.tcp.in.ngrok.io',
#            'PORT': '16681',
#        }
#    }
#else:
#    DATABASES = {
#        'default': {
#            'ENGINE': 'django.db.backends.sqlite3',
#            'NAME': BASE_DIR / 'db.sqlite3',
#        }
#    }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'en-us'

USE_I18N = True
USE_L10N = True

USE_TZ = True
TIME_ZONE = 'UTC'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

# Configuración de WhiteNoise
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'django_debug.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'apimovil': {  # reemplaza 'app' con el nombre de tu aplicación
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
